In [1]:
# vector
a = [1, 2, 3, 4]
print(type(a))

## Basic list in python is not really a vector for ML

<class 'list'>


In [9]:
# enters numpy

import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
print("u, v: ", u, v)
print("shape: ", u.shape, v.shape)
print("data type:", u.dtype, v.dtype)
print("number of dimensions: ", u.ndim, v.ndim)

print("broadcast, element wise multiplication:", u*v)
print("dot product of two vectors: ", np.dot(u, v))

u, v:  [1 2 3] [4 5 6]
shape:  (3,) (3,)
data type: int64 int64
number of dimensions:  1 1
broadcast, element wise multiplication: [ 4 10 18]
dot product of two vectors:  32


In [27]:
# Let's look at closures and Axioms

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
w = u + v
print("u, v, w: ", u, v, w)
print("shapes: ", u.shape, v.shape, w.shape)
print("dimensions: ", u.ndim, v.ndim, w.ndim)
print("u + v belongs to V")

w = np.array([7, 8, 9])
print("associativity:: u + (v + w) = (u + v) + w => ", u + (v + w), (u + v) + w)
print("commutativity:: u + v = v + u => ", u + v, v + u, np.array_equal(u + v, v + u))
zero = np.array([0, 0, 0])
print("zero vector:: u + 0 = 0 + u = u => ", u + zero, zero + u)
inverse = np.array([-1, -2, -3])
print("inverse:: u + (-u) = 0 => ", u + inverse)

print("scaling:: n(v) = nv => vector belonging to same vector space")
su = 3 * u
print("vectors u, su: ", u, su)
print("shapes: ", u.shape, su.shape)
print("dimensions: ", u.ndim, su.ndim)
print("nv belongs to V")

print("unit multiplication identity:: 1v = v => ", 1 * v, v)
print("c(u + v) = cu + cv:: ", 3*(u + v), 3*u + 3*v)
print("(c+d)u = cu + du):: ", (1 + 2)*u, u + 2*u)
print("c(du) = cd(u):: ", 3*(4*u), 12*u)

print("Both closures and all eigth axioms are written above in numpy code")
# could have used np.array_equal(u, v) more....

u, v, w:  [1 2 3] [4 5 6] [5 7 9]
shapes:  (3,) (3,) (3,)
dimensions:  1 1 1
u + v belongs to V
associativity:: u + (v + w) = (u + v) + w =>  [12 15 18] [12 15 18]
commutativity:: u + v = v + u =>  [5 7 9] [5 7 9] True
zero vector:: u + 0 = 0 + u = u =>  [1 2 3] [1 2 3]
inverse:: u + (-u) = 0 =>  [0 0 0]
scaling:: n(v) = nv => vector belonging to same vector space
vectors u, su:  [1 2 3] [3 6 9]
shapes:  (3,) (3,)
dimensions:  1 1
nv belongs to V
unit multiplication identity:: 1v = v =>  [4 5 6] [4 5 6]
c(u + v) = cu + cv::  [15 21 27] [15 21 27]
(c+d)u = cu + du)::  [3 6 9] [3 6 9]
c(du) = cd(u)::  [12 24 36] [12 24 36]
Both closures and all eigth axioms are written above in numpy code


In [ ]:
# Vector Space::
# Addition:
# 1. closure
# 2. associativity
# 3. commutativity
# 4. additive identity
# 5. additive inverse

# Scalar multiplication:
# 6. closure
# 7. scalar identity
# 8. distributivity over vector addition
# 9. distributivity over scalar addition
# 10. compatibility of scalar multiplication

Topic: Vectors, components, vector operations, dot products, shapes, and NumPy

---

## Problem 1 - Tensor shape

Use the code below.

Find the shape, number of dimensions, and number of elements for each object.

```python
import numpy as np

u = np.array([1, 2, 3])

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

X = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

# For each object, answer:
#
# u:
# shape =
# ndim =
# number of elements =
#
# A:
# shape =
# ndim =
# number of elements =
#
# X:
# shape =
# ndim =
# number of elements =

print("u:")
print("shape:", u.shape)
print("ndim:", u.ndim)
print("size:", u.size)

print("\nA:")
print("shape:", A.shape)
print("ndim:", A.ndim)
print("size:", A.size)

print("\nX:")
print("shape:", X.shape)
print("ndim:", X.ndim)
print("size:", X.size)
```

Question:

What does each axis of `X` represent?

---

## Problem 2 - Vector operations by hand

Given these two vectors:

```python
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
```

Calculate each result by hand before running the code.

```python
# Calculate by hand:
#
# u + v =
# u - v =
# 3u =
# -2v =
# u dot v =

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

print("u + v =", u + v)
print("u - v =", u - v)
print("3u =", 3 * u)
print("-2v =", -2 * v)
print("u dot v =", u @ v)
```

---

## Problem 3 - Write a vector operations function

Write a function that returns:

```text
u + v
u - v
u dot v
length of u
```

Do not use a loop.

```python
import numpy as np

def vector_operations(u, v):
    # Return the four requested results.
    #
    # 1. vector addition
    # 2. vector subtraction
    # 3. dot product
    # 4. Euclidean length of u
    #
    # Write your code here.
    pass


u = np.array([3, 4])
v = np.array([1, 2])

result = vector_operations(u, v)

print(result)
```

Expected structure:

```text
(
    u + v,
    u - v,
    u dot v,
    length of u
)
```

---

## Problem 4 - Stable softmax

Run this code.

```python
import numpy as np

x = np.array([1000.0, 1001.0, 1002.0])

# This is the direct softmax formula.
# It may have a numerical problem.

p = np.exp(x) / np.sum(np.exp(x))

print(p)
```

Answer these questions in your own words:

```text
1. What happened?

2. Why did it happen?

3. Why can exp(x) become a problem for large values?

4. How can we make softmax more stable?
```

Now implement the stable version.

```python
def stable_softmax(x):
    # Subtract the largest value first.
    # Then calculate the exponentials.
    #
    # Write your code here.
    pass


x = np.array([1000.0, 1001.0, 1002.0])

p = stable_softmax(x)

print(p)
print("sum =", np.sum(p))
```

Check that the probabilities sum to 1.

---

## Problem 5 - Broadcasting and shapes

Look at this code before running it.

```python
import numpy as np

u = np.array([1, 2, 3])
v = np.array([[4, 5, 6]])

result = u + v

print(result)
print(result.shape)
```

Answer first:

```text
1. Shape of u =
2. Shape of v =
3. Shape of result =
4. Why does NumPy allow this addition?
5. Is v a 1-dimensional vector?
```

Now run the code.

Then create a second version of `v`:

```python
# Create v as a real 1-dimensional vector.
# Then add it to u.

u = np.array([1, 2, 3])

# Write your code here.
```

---

## Problem 6 - Test the vector axioms

Use three different vectors.

```python
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
w = np.array([7, 8, 9])

# Test associativity:
#
# u + (v + w) = (u + v) + w

left = u + (v + w)
right = (u + v) + w

print("associativity:")
print("left :", left)
print("right:", right)
print("equal:", np.array_equal(left, right))


# Test commutativity:
#
# u + v = v + u

left = u + v
right = v + u

print("\ncommutativity:")
print("left :", left)
print("right:", right)
print("equal:", np.array_equal(left, right))


# Test the zero vector:
#
# u + 0 = u

zero = np.array([0, 0, 0])

print("\nzero vector:")
print("u + zero =", u + zero)
print("equal    =", np.array_equal(u + zero, u))


# Test the additive inverse:
#
# u + (-u) = 0

inverse = -u

print("\nadditive inverse:")
print("u + (-u) =", u + inverse)
```

Question:

Why does this code demonstrate the axioms but not prove them mathematically?

---

## Problem 7 - Scalar multiplication

Use the vector below.

```python
import numpy as np

u = np.array([1, 2, 3])

# Test scalar multiplication with different scalars.

for c in [0, 1, 2, -1, -3, 0.5]:
    print("c =", c, "  cu =", c * u)
```

Answer:

```text
1. What happens when c = 0?

2. What happens when c = 1?

3. What happens when c = -1?

4. What happens to the length when c = 2?

5. What happens to the direction when c is negative?
```

Then verify:

```text
c(u + v) = cu + cv
```

with NumPy.

---

## Problem 8 - Dot product and geometry

Start with perpendicular vectors.

```python
import numpy as np

u = np.array([1, 0])
v = np.array([0, 1])

dot = u @ v

print("dot product =", dot)
```

Explain:

```text
Why is the dot product zero?

What does this tell us about the two vectors?
```

Now try vectors pointing in the same direction.

```python
u = np.array([1, 0])
v = np.array([2, 0])

print("dot product =", u @ v)
```

Now try vectors pointing in opposite directions.

```python
u = np.array([1, 0])
v = np.array([-2, 0])

print("dot product =", u @ v)
```

Explain what changed in each case.

---

## Problem 9 - Elementwise multiplication vs dot product

Use:

```python
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

a = u * v
b = u @ v

print("u * v =", a)
print("u @ v =", b)

print("shape of u * v:", a.shape)
print("shape of u @ v:", np.shape(b))
```

Answer:

```text
1. What does u * v do?

2. What does u @ v do?

3. Why is u * v a vector?

4. Why is u @ v a scalar?

5. Which one represents the dot product?
```

---

## Problem 10 - Matrix times vector

Given:

```python
import numpy as np

x = np.array([1, 2, 3])

A = np.array([
    [2, 0, 1],
    [1, 3, 0],
    [0, 1, 2]
])

# Calculate Ax by hand first.
#
# Ax =
#
# Then calculate it with NumPy.

y = A @ x

print("A:")
print(A)

print("\nx:")
print(x)

print("\nAx:")
print(y)

print("\nShape of Ax:")
print(y.shape)
```

Answer:

```text
1. What is x?

2. What is A?

3. What does Ax mean?

4. What is the shape of Ax?

5. Is Ax a vector or a matrix?

6. What does A do to x geometrically?
```

Finally compare:

```python
print("A @ x =", A @ x)
print("A * x =", A * x)
```

Explain why these two operations are different.

---

# Day 1 Interview Questions

After solving the problems, answer these without looking at your notes.

## Question 1

What is a vector?

## Question 2

What is a component of a vector?

## Question 3

What is the difference between vector addition and scalar multiplication?

## Question 4

What does the dot product tell us geometrically?

## Question 5

Why does:

```text
u dot v = 0
```

mean that two non-zero vectors are perpendicular?

## Question 6

What is the difference between:

```python
u * v
```

and:

```python
u @ v
```

## Question 7

What does the shape:

```text
(32, 128, 768)
```

tell you, and what does it not tell you?

## Question 8

What is broadcasting?

## Question 9

Why can NumPy execute:

```python
np.array([1, 2, 3]) + np.array([[4, 5, 6]])
```

without raising an error?

## Question 10

Why is running a few NumPy examples not a mathematical proof of a vector-space axiom?


In [42]:
# Vector addition
## how to get shape of a given vector?: np.array([1, 2, 3]).shape
### how to get number of elements: np.array([1, 2, 3]).shape[0]

v = np.array([1, 2, 3])
print(v, v.shape, v.shape[0], v.dtype)

## how to loop over a np vector?
for i in range(v.shape[0]):
    print(i)

## how to create an empty vector?
e = np.empty(v.shape, v.dtype)
print(e, e.shape, e.shape[0], e.dtype)

## how to set value in a vector at a given vertex
e[0] = v[0]+1
e[1] = v[1]+1
e[2] = v[2]+1
# e[3] = v[3]+1 # IndexError: index 3 is out of bounds for axis 0 with size 3
print(e)

## full function

def vector_addition_1(u, v):
    ushp, vshp = u.shape, v.shape
    if ushp != vshp:
        print("Different shape vectors cannot be added atm.")
        return np.zeros(1, dtype="int64")

    return np.ones(1)

print(vector_addition_1(np.array([1, 2, 3]), np.array([[1, 2], [4, 5]]))) 
# Different shape vectors cannot be added atm.
# [0]

def vector_addition_2(u, v):
    ushp, vshp = u.shape, v.shape
    if ushp != vshp:
        print("Different shape vectors cannot be added atm.")
        return np.zeros(1, dtype="int64")

    udt, vdt = u.dtype, v.dtype
    if udt != vdt:
        print("Different data typed vectors cannot be added atm.")
        return np.zeros(1, dtype=udt)

    return np.ones(1)

print(vector_addition_2(np.array([1, 2, 3]), np.array([1.0, 2.0, 3.0]))) 
# Different data typed vectors cannot be added atm.
# [0]

def vector_addition_3(u, v):
    ushp, vshp = u.shape, v.shape
    if ushp != vshp:
        print("Different shape vectors cannot be added atm.")
        return np.zeros(1, dtype="int64")

    udt, vdt = u.dtype, v.dtype
    if udt != vdt:
        print("Different data typed vectors cannot be added atm.")
        return np.zeros(1, dtype=udt)

    e = np.empty(ushp, udt)
    for i in range(ushp[0]):
        e[i] = u[i] + v[i]
        
    return e

print(vector_addition_3(np.array([1, 2, 3]), np.array([1.0, 2.0, 3.0], dtype="int64"))) 
# [2 4 6]
print(vector_addition_3(np.array([1, 2, 3]), np.array([-1, -2, -3]))) 
# [0 0 0]

[1 2 3] (3,) 3 int64
0
1
2
[1 2 3] (3,) 3 int64
[2 3 4]
Different shape vectors cannot be added atm.
[0]
Different data typed vectors cannot be added atm.
[0]
[2 4 6]
[0 0 0]


In [46]:
def vector_addition(u, v):
    ushp, vshp = u.shape, v.shape
    if ushp != vshp:
        print("Different shape vectors cannot be added atm.")
        return np.zeros(1, dtype="int64")

    udt, vdt = u.dtype, v.dtype
    if udt != vdt:
        print("Different data typed vectors cannot be added atm.")
        return np.zeros(1, dtype=udt)

    e = np.empty(ushp, udt)
    for i in np.ndindex(ushp):
        e[i] = u[i] + v[i]
        
    return e


print(vector_addition(np.array([1, 2, 3]), np.array([1.0, 2.0, 3.0], dtype="int64"))) 
# [2 4 6]
print(vector_addition(np.array([1, 2, 3]), np.array([-1, -2, -3]))) 
# [0 0 0]
print(vector_addition(np.array([[1, 2], [3, 4]]), np.array([[1, 2], [3, 4]])))
# [[2 4]
#  [6 8]]
## Glory to np.ndindex which takes care of proper indexing. Yayiya!


[2 4 6]
[0 0 0]
[[2 4]
 [6 8]]


In [49]:
def vector_subtraction(u, v):
    ushp, vshp = u.shape, v.shape
    if ushp != vshp:
        print("Different shape vectors cannot be subtracted atm.")
        return np.zeros(1, dtype="int64")

    udt, vdt = u.dtype, v.dtype
    if udt != vdt:
        print("Different data typed vectors cannot be subtracted atm.")
        return np.zeros(1, dtype=udt)

    e = np.empty(ushp, udt)
    for i in np.ndindex(ushp):
        e[i] = u[i] - v[i]
        
    return e

print(vector_subtraction(np.array([1, 2, 3]), np.array([1.0, 2.0, 3.0], dtype="int64"))) 
# [0 0 0]
print(vector_subtraction(np.array([1, 2, 3]), np.array([-1, -2, -3]))) 
# [2 4 6]
print(vector_subtraction(np.array([[1, 2], [3, 4]]), np.array([[1, 2], [3, 4]])))
# [[0 0]
#  [0 0]]

[0 0 0]
[2 4 6]
[[0 0]
 [0 0]]


In [56]:
def vector_dot_product_1(u, v):
    ushp, vshp = u.shape, v.shape
    if ushp != vshp:
        print("Different shapes.")
        return -1

    udt, vdt = u.dtype, v.dtype
    if udt != vdt:
        print("Different data types.")
        return -1

    out = 0
    for i in range(ushp[0]):
        out += u[i]*v[i]

    return out

print(vector_dot_product_1(np.array([1, 2, 3]), np.array([4, 5, 6])))
# 32

def vector_dot_product(u, v):
    ushp, vshp = u.shape, v.shape
    if ushp != vshp:
        print("Different shapes.")
        return -1

    udt, vdt = u.dtype, v.dtype
    if udt != vdt:
        print("Different data types.")
        return -1

    out = 0
    for i in np.ndindex(ushp):
        out += u[i]*v[i]

    return out

print(vector_dot_product(np.array([1, 2, 3]), np.array([4, 5, 6])))
# 32
print(vector_dot_product(np.array([[1, 2], [3, 4]]), np.array([[1, 2], [3, 4]])))

32
32
30


In [61]:
u, v = np.array([1, 2, 3]), np.array([4, 5, 6])

for i in np.ndindex(u.shape):
    print(i)

(0,)
(1,)
(2,)
